config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists do
    resources :bookmarks, except: :destroy
    resources :reviews, except: :destroy
  end
  resources :bookmarks, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  # validates :comment, presence: true, uniqueness: true
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :comment, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @review = Review.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
  @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private
  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

<p> <%= link_to 'cancel', list_path(@list) %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1 style="color: black">Save any kind of movies</h1>
    <h3 class="typed-js"></h3>
  </div>
</div>
<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h3 class="mb-0">My Lists</h3>
    <%= link_to 'Create a movie list', new_list_path, class: 'btn btn-flat' %>
  </div>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-12 colsm-6 col-md-4">
        <div class="card bg-light m-2 p-2 rounded">
           <%= link_to list_path(list), class:'text-decoration-none' do %>
           <div class="card-product rounded">
             <%= cl_image_tag(list.photo.key,
             width: 200, height: 150, crop: :fill) %>
             <div class="card-product-infos">
               <p><%= list.name %></p>
             </div>
           </div>
        </div>

        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Drama' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
      <p> <%= link_to 'cancel', lists_path %> </p>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class=" row justify-content-between p-5">
    <h2><%= @list.name %></h2>
    <p> <%= link_to 'add a new movie', new_list_bookmark_path(@list) %></p>
  </div>
</div>

<div class="container">
  <% @list.movies.each do |movie| %>
    <div class="d-flex justify-content-center m-4">
        <div class="col-12 col-lg-9">
          <div class="card bg-light p-5">
            <p style="text-align: center;"><%= movie.title %></p>
            <div class="card-product">
              <%= image_tag movie.poster_url, alt: movie.title, class: 'movie-img w-25'%>
              <div class="card-movie-infos p-3">
                <p><%= movie.overview %></p>
                 <small class="flex-shrink-0"><%= link_to 'delete', bookmark_path(Bookmark.find_by(list: @list, movie: movie)), method: :delete, data: { confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
              </div>
            </div>
          </div>
        </div>
    </div>
  <% end %>
</div>



<p class="p-5"><%= link_to 'back', lists_path %></p>

<p> <%= link_to 'add a new review', new_list_review_path(@list) %></p>

app/views/reviews/_form.html.erb
<!--         <h3>Create a new review</h3>
        <%= simple_form_for review do |f| %>
          <%= f.input :comment, placeholder: 'Drama' %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %> -->

app/views/reviews/new.html.erb
<div class="col-12 col-sm-6">
  <div class="bg-white rounded p-3">
    <h5>Add your review</h5>
    <%= simple_form_for [@list, @review] do |f| %>
      <%= f.input :comment, placeholder: 'Add your review here...' %>
      <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "What's your rating", input_html: { id: 'review_rating' } %>
      <%= f.submit class:'btn btn-flat' %>
    <% end %>
  </div>
</div>

<p class="p-5"><%= link_to 'back', list_path(@list) %></p>